version: '3'
services:

  db:
    image: postgres:12-bullseye
    container_name: pgres
    healthcheck:
      test: "exit 0"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: socntw

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: pwd
      DB_NAME: socntw
    links:
      - db
    depends_on:
      - db

  redis:
    image: redis:bookworm
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/root/redis
    environment:
      - REDIS_PASSWORD=pwd
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  coordinator:
    image: citusdata/citus:alpine
    container_name: citus_coordinator
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: cdb
    command: >
      postgres -c 'shared_preload_libraries=citus' 
               -c 'citus.node_conninfo="host=coordinator port=5433"'

  worker1:
    image: citusdata/citus:alpine
    container_name: citus_worker1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: cdb
    command: >
      postgres -c 'shared_preload_libraries=citus' 
               -c 'citus.node_conninfo="host=worker1 port=5433"'

  worker2:
    image: citusdata/citus:alpine
    container_name: citus_worker2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: cdb
    command: >
      postgres -c 'shared_preload_libraries=citus' 
               -c 'citus.node_conninfo="host=worker2 port=5433"'

volumes:
  db_data: